// 자동 생성하지 말고 직접 다듬어 쓰는 초기 콘텐츠. 기획안 6장 기준: 구체적이되 해석을 닫지 않는다.
import type { Token, QuestionCard } from './types';

export const objectTokens: Token[] = [
  { id: 'o01', pouch: 'A', label: '우산', code: 'UMBRELLA' },
  { id: 'o02', pouch: 'A', label: '열쇠', code: 'KEY' },
  { id: 'o03', pouch: 'A', label: '식탁', code: 'TABLE' },
  { id: 'o04', pouch: 'A', label: '구두', code: 'SHOE' },
  { id: 'o05', pouch: 'A', label: '라디오', code: 'RADIO' },
  { id: 'o06', pouch: 'A', label: '자전거', code: 'BICYCLE' },
  { id: 'o07', pouch: 'A', label: '찻잔', code: 'TEACUP' },
  { id: 'o08', pouch: 'A', label: '등대', code: 'LIGHTHOUSE' },
  { id: 'o09', pouch: 'A', label: '우체통', code: 'MAILBOX' },
  { id: 'o10', pouch: 'A', label: '손목시계', code: 'WATCH' },
  { id: 'o11', pouch: 'A', label: '거울', code: 'MIRROR' },
  { id: 'o12', pouch: 'A', label: '사다리', code: 'LADDER' },
  { id: 'o13', pouch: 'A', label: '편지봉투', code: 'ENVELOPE' },
  { id: 'o14', pouch: 'A', label: '성냥', code: 'MATCH' },
  { id: 'o15', pouch: 'A', label: '연필', code: 'PENCIL' },
  { id: 'o16', pouch: 'A', label: '지도', code: 'MAP' },
  { id: 'o17', pouch: 'A', label: '망원경', code: 'TELESCOPE' },
  { id: 'o18', pouch: 'A', label: '나침반', code: 'COMPASS' },
  { id: 'o19', pouch: 'A', label: '모래시계', code: 'HOURGLASS' },
  { id: 'o20', pouch: 'A', label: '전화기', code: 'TELEPHONE' },
  { id: 'o21', pouch: 'A', label: '계단', code: 'STAIRS' },
  { id: 'o22', pouch: 'A', label: '창문', code: 'WINDOW' },
  { id: 'o23', pouch: 'A', label: '이불', code: 'BLANKET' },
  { id: 'o24', pouch: 'A', label: '바늘', code: 'NEEDLE' },
  { id: 'o25', pouch: 'A', label: '실타래', code: 'YARN' },
  { id: 'o26', pouch: 'A', label: '단추', code: 'BUTTON' },
  { id: 'o27', pouch: 'A', label: '안경', code: 'GLASSES' },
  { id: 'o28', pouch: 'A', label: '모자', code: 'HAT' },
  { id: 'o29', pouch: 'A', label: '장갑', code: 'GLOVE' },
  { id: 'o30', pouch: 'A', label: '목도리', code: 'SCARF' },
  { id: 'o31', pouch: 'A', label: '양초', code: 'CANDLE' },
  { id: 'o32', pouch: 'A', label: '램프', code: 'LAMP' },
  { id: 'o33', pouch: 'A', label: '주전자', code: 'KETTLE' },
  { id: 'o34', pouch: 'A', label: '숟가락', code: 'SPOON' },
  { id: 'o35', pouch: 'A', label: '접시', code: 'PLATE' },
  { id: 'o36', pouch: 'A', label: '유리병', code: 'BOTTLE' },
  { id: 'o37', pouch: 'A', label: '종', code: 'BELL' },
  { id: 'o38', pouch: 'A', label: '피아노', code: 'PIANO' },
  { id: 'o39', pouch: 'A', label: '오르골', code: 'MUSICBOX' },
  { id: 'o40', pouch: 'A', label: '카메라', code: 'CAMERA' },
  { id: 'o41', pouch: 'A', label: '사진첩', code: 'ALBUM' },
  { id: 'o42', pouch: 'A', label: '공책', code: 'NOTEBOOK' },
  { id: 'o43', pouch: 'A', label: '책갈피', code: 'BOOKMARK' },
  { id: 'o44', pouch: 'A', label: '달력', code: 'CALENDAR' },
  { id: 'o45', pouch: 'A', label: '의자', code: 'CHAIR' },
  { id: 'o46', pouch: 'A', label: '문고리', code: 'DOORKNOB' },
  { id: 'o47', pouch: 'A', label: '커튼', code: 'CURTAIN' },
  { id: 'o48', pouch: 'A', label: '화분', code: 'FLOWERPOT' },
  { id: 'o49', pouch: 'A', label: '물뿌리개', code: 'SPRINKLER' },
  { id: 'o50', pouch: 'A', label: '빗자루', code: 'BROOM' },
  { id: 'o51', pouch: 'A', label: '바구니', code: 'BASKET' },
  { id: 'o52', pouch: 'A', label: '여행가방', code: 'SUITCASE' },
  { id: 'o53', pouch: 'A', label: '기차표', code: 'TICKET' },
  { id: 'o54', pouch: 'A', label: '엽서', code: 'POSTCARD' },
  { id: 'o55', pouch: 'A', label: '벽시계', code: 'CLOCK' },
  { id: 'o56', pouch: 'A', label: '풍선', code: 'BALLOON' },
  { id: 'o57', pouch: 'A', label: '연', code: 'KITE' },
  { id: 'o58', pouch: 'A', label: '조개껍데기', code: 'SEASHELL' },
  { id: 'o59', pouch: 'A', label: '돌멩이', code: 'PEBBLE' },
  { id: 'o60', pouch: 'A', label: '깃털', code: 'FEATHER' },
];

export const attributeTokens: Token[] = [
  { id: 'a01', pouch: 'B', label: '그물망처럼 구멍이 난' },
  { id: 'a02', pouch: 'B', label: '속이 비치는' },
  { id: 'a03', pouch: 'B', label: '시간을 거슬러 닳는' },
  { id: 'a04', pouch: 'B', label: '이름을 기억하는' },
  { id: 'a05', pouch: 'B', label: '물에 뜨지 않는' },
  { id: 'a06', pouch: 'B', label: '밤에만 따뜻한' },
  { id: 'a07', pouch: 'B', label: '소리를 삼키는' },
  { id: 'a08', pouch: 'B', label: '그림자가 두 개인' },
  { id: 'a09', pouch: 'B', label: '한 번 쓰면 잊히는' },
  { id: 'a10', pouch: 'B', label: '비가 올 때만 보이는' },
  { id: 'a11', pouch: 'B', label: '주인을 고르는' },
  { id: 'a12', pouch: 'B', label: '조금씩 가벼워지는' },
  { id: 'a13', pouch: 'B', label: '거꾸로 자라는' },
  { id: 'a14', pouch: 'B', label: '꿈을 담아 두는' },
  { id: 'a15', pouch: 'B', label: '만질 때마다 색이 바뀌는' },
  { id: 'a16', pouch: 'B', label: '먼 곳의 냄새가 나는' },
  { id: 'a17', pouch: 'B', label: '절반만 존재하는' },
  { id: 'a18', pouch: 'B', label: '계절을 늦추는' },
  { id: 'a19', pouch: 'B', label: '거짓말을 못 하는' },
  { id: 'a20', pouch: 'B', label: '누군가를 기다리는' },
  { id: 'a21', pouch: 'B', label: '속삭임으로 움직이는' },
  { id: 'a22', pouch: 'B', label: '빛을 흘리는' },
  { id: 'a23', pouch: 'B', label: '녹슬지 않는' },
  { id: 'a24', pouch: 'B', label: '아무도 끝까지 본 적 없는' },
  { id: 'a25', pouch: 'B', label: '두 사람만 쓸 수 있는' },
  { id: 'a26', pouch: 'B', label: '안쪽이 바깥보다 넓은' },
  { id: 'a27', pouch: 'B', label: '잠든 동안 이동하는' },
  { id: 'a28', pouch: 'B', label: '오래된 노래를 흥얼거리는' },
  { id: 'a29', pouch: 'B', label: '바람을 모으는' },
  { id: 'a30', pouch: 'B', label: '눈을 감아야 보이는' },
  { id: 'a31', pouch: 'B', label: '주인을 따라 하는' },
  { id: 'a32', pouch: 'B', label: '점점 투명해지는' },
  { id: 'a33', pouch: 'B', label: '별자리가 새겨진' },
  { id: 'a34', pouch: 'B', label: '한쪽으로만 열리는' },
  { id: 'a35', pouch: 'B', label: '남의 목소리로 말하는' },
  { id: 'a36', pouch: 'B', label: '물결처럼 흔들리는' },
  { id: 'a37', pouch: 'B', label: '하루에 한 번 멈추는' },
  { id: 'a38', pouch: 'B', label: '잃어버린 것을 부르는' },
  { id: 'a39', pouch: 'B', label: '기분에 따라 무거워지는' },
  { id: 'a40', pouch: 'B', label: '끝없이 이어지는' },
  { id: 'a41', pouch: 'B', label: '조각난 채로 작동하는' },
  { id: 'a42', pouch: 'B', label: '이끼가 자라는' },
  { id: 'a43', pouch: 'B', label: '달빛에 녹는' },
  { id: 'a44', pouch: 'B', label: '뒤돌아보면 사라지는' },
  { id: 'a45', pouch: 'B', label: '기억보다 조금 큰' },
  { id: 'a46', pouch: 'B', label: '소금 맛이 나는' },
  { id: 'a47', pouch: 'B', label: '새벽에만 깨어 있는' },
  { id: 'a48', pouch: 'B', label: '먼지가 쌓이지 않는' },
  { id: 'a49', pouch: 'B', label: '손때가 반짝이는' },
  { id: 'a50', pouch: 'B', label: '다른 시대에서 온' },
  { id: 'a51', pouch: 'B', label: '열이 나면 우는' },
  { id: 'a52', pouch: 'B', label: '이야기를 요구하는' },
  { id: 'a53', pouch: 'B', label: '겹겹이 접힌' },
  { id: 'a54', pouch: 'B', label: '서로를 끌어당기는' },
  { id: 'a55', pouch: 'B', label: '누구의 것도 아닌' },
  { id: 'a56', pouch: 'B', label: '가장자리가 흐린' },
  { id: 'a57', pouch: 'B', label: '암호를 물어보는' },
  { id: 'a58', pouch: 'B', label: '노을 색으로 물든' },
  { id: 'a59', pouch: 'B', label: '숨을 쉬는' },
  { id: 'a60', pouch: 'B', label: '언젠가 돌려주어야 하는' },
];

export const questionCards: QuestionCard[] = [
  { id: 'q01', category: 'use', text: '누가 이 물건을 가장 필요로 하며 왜 그런가', choices: ["길을 잃은 여행자", "잠들지 못하는 아이", "기억을 잃어 가는 노인"] },
  { id: 'q02', category: 'use', text: '이 물건은 하루 중 언제 가장 바쁜가', choices: ["해 뜨기 직전", "모두가 잠든 한밤", "비가 그친 직후"] },
  { id: 'q03', category: 'use', text: '이 물건을 처음 만든 사람은 무엇을 해결하고 싶었나', choices: ["외로움", "잊어버리는 일", "너무 긴 기다림"] },
  { id: 'q04', category: 'use', text: '이 물건을 잘못 쓰면 어떤 일이 생기나', choices: ["엉뚱한 사람에게 닿는다", "시간이 조금 어긋난다", "주인이 바뀐다"] },
  { id: 'q05', category: 'use', text: '이 물건으로 할 수 있는 가장 작은 친절은 무엇인가', choices: ["누군가의 이름을 불러 준다", "잃어버린 소리를 돌려준다", "젖은 마음을 말려 준다"] },
  { id: 'q06', category: 'cost', text: '이 물건을 사용할 때 반드시 잃는 것은 무엇인가', choices: ["기억 하나", "목소리 한 마디", "하루치 그림자"] },
  { id: 'q07', category: 'cost', text: '이 물건을 가지려면 무엇을 내주어야 하나', choices: ["가장 좋아하는 단어", "한 계절", "비밀 하나"] },
  { id: 'q08', category: 'cost', text: '이 물건을 너무 오래 쓰면 몸에 어떤 흔적이 남나', choices: ["손끝이 투명해진다", "꿈을 꾸지 않게 된다", "이름이 흐려진다"] },
  { id: 'q09', category: 'cost', text: '이 물건을 쓰지 않기로 한 사람은 무엇을 지키려 했나', choices: ["첫 번째 기억", "누군가와의 약속", "자신의 얼굴"] },
  { id: 'q10', category: 'cost', text: '이 물건의 값은 무엇으로 치르나', choices: ["이야기 한 편", "잠 한 시간", "웃음 한 번"] },
  { id: 'q11', category: 'place', text: '이 물건은 어디에서만 작동하는가', choices: ["비가 그치지 않는 도시", "바다 밑 도서관", "지도에 없는 역"] },
  { id: 'q12', category: 'place', text: '이 물건이 가장 많이 모여 있는 곳은 어디인가', choices: ["오래된 시장 골목", "버려진 천문대", "모두가 떠난 학교"] },
  { id: 'q13', category: 'place', text: '이 물건을 가지고 들어갈 수 없는 곳은 어디인가', choices: ["거울 속 방", "새벽의 정원", "기억의 박물관"] },
  { id: 'q14', category: 'place', text: '이 물건이 태어난 곳의 날씨는 어떤가', choices: ["늘 안개가 낀다", "눈이 위로 내린다", "하루에 노을이 두 번 진다"] },
  { id: 'q15', category: 'place', text: '이 물건을 수리하는 가게는 어디에 있나', choices: ["구름 위 다락방", "지하철 마지막 칸", "등대 꼭대기"] },
  { id: 'q16', category: 'memory', text: '이 물건이 마지막으로 기억하는 사람은 누구인가', choices: ["우산을 두고 간 아이", "편지를 쓰다 만 사람", "이름 없는 수선공"] },
  { id: 'q17', category: 'memory', text: '이 물건이 절대 잊지 못하는 날은 언제인가', choices: ["처음 비가 내린 날", "도시의 불이 꺼진 날", "누군가 돌아오지 않은 날"] },
  { id: 'q18', category: 'memory', text: '이 물건에 남아 있는 가장 오래된 소리는 무엇인가', choices: ["자장가", "기차 기적 소리", "문 닫히는 소리"] },
  { id: 'q19', category: 'memory', text: '이 물건은 누구의 꿈을 대신 꾸고 있나', choices: ["떠나간 친구", "아직 태어나지 않은 아이", "도시 전체"] },
  { id: 'q20', category: 'memory', text: '이 물건을 만지면 떠오르는 장면은 무엇인가', choices: ["빈 운동장", "불 켜진 부엌", "젖은 기차역"] },
  { id: 'q21', category: 'society', text: '이 물건 때문에 생긴 직업이나 금기는 무엇인가', choices: ["기억을 수선하는 장인", "밤에 이름을 부르지 않는 금기", "물건을 돌려주는 배달부"] },
  { id: 'q22', category: 'society', text: '사람들은 이 물건을 어떻게 나누어 쓰나', choices: ["마을 광장에 하나만 둔다", "생일마다 다음 사람에게 넘긴다", "아무도 모르게 빌려 간다"] },
  { id: 'q23', category: 'society', text: '이 물건을 둘러싼 축제나 의식은 무엇인가', choices: ["첫눈 오는 날 함께 연다", "일 년에 한 번 모두 바꾼다", "떠나는 사람에게 건넨다"] },
  { id: 'q24', category: 'society', text: '이 물건을 가진 사람을 사람들은 뭐라고 부르나', choices: ["보관인", "빗소리 사람", "두 번째 이웃"] },
  { id: 'q25', category: 'society', text: '이 물건을 두고 벌어진 가장 큰 다툼은 무엇이었나', choices: ["누가 먼저 기억할지", "어디에 묻을지", "누구의 이름을 새길지"] },
  { id: 'q26', category: 'change', text: '오늘 처음으로 이 물건에 생긴 이상은 무엇인가', choices: ["모든 구멍이 닫혔다", "낯선 이름을 불렀다", "그림자가 사라졌다"] },
  { id: 'q27', category: 'change', text: '백 년 뒤 이 물건은 어떻게 바뀌어 있을까', choices: ["아무도 쓰는 법을 모른다", "스스로 주인을 찾는다", "노래가 된다"] },
  { id: 'q28', category: 'change', text: '이 물건이 부서지면 무엇이 쏟아져 나오나', choices: ["오래된 빗물", "잠든 목소리들", "접혀 있던 계절"] },
  { id: 'q29', category: 'change', text: '이 물건이 자라거나 줄어드는 조건은 무엇인가', choices: ["누군가 울 때", "보름달이 뜰 때", "거짓말을 들을 때"] },
  { id: 'q30', category: 'change', text: '이 물건이 사라지면 세계는 무엇을 잃나', choices: ["비의 기억", "밤의 온기", "약속의 무게"] },
];
